name: Update Streak Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download streak image
        run: |
             curl -s "https://streak-stats.demolab.com?user=rubabshaukatalidev&theme=react&hide_border=true&fire=FF7F00" -o assets/streak-stats.svg
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/streak-stats.svg
          git diff --staged --quiet || git commit -m "Update streak stats"
          git push
